### ISSUE TITLE
The app erase the window.rudderanalytics object

### ISSUE THREAD

**Issue by duannx** [rudderlabs/rudder-shopify-tracker#18]
# Problem
In the `loadingCode.js` file
```js
rudderanalytics = window.rudderanalytics = [];
```
This line is overwriting the current `window.rudderanalytics`. It happens when we want to fire some methods before the SDK is loaded in another script so we need to add the methods to `window.rudderanalytics`. Although currently, the SDK is ignored all the methods that are called before the `load` method. But I believe that it will change in the future. I already raised [an issue](https://github.com/rudderlabs/rudder-sdk-js/issues/503) about it in the SDK repo.

# Suggeted solution
It should be changed to: 
```js
rudderanalytics = window.rudderanalytics || [];
```

# Alternative
By the way, we are loading the SDK synchronously as the code in the `router.js` file
```js
let d = fs.readFileSync("./loadingCode.js", {
    encoding: "utf-8",
});
ctx.response.body = d + rudderJsCode + deviceModeInit;
```
So I think we don't need to mock the `rudderanalytics` object in `loadingCode.js`. We just need to remove all the mocking code and move the order of `loadingCode.js` after the `rudderJsCode`
The code in `loadingCode.js` should be changed to: 
```js
(function () {
 // all the mocking code before are removed
  rudderanalytics.load("writeKey", "https://dataPlaneUrl", {
    configUrl: "configBackendUrl",
    logLevel: "DEBUG",
  });
})();
```
And the order of code in `router.js` should be changed to: 
```js
let d = fs.readFileSync("./loadingCode.js", {
    encoding: "utf-8",
});
ctx.response.body = rudderJsCode + d + deviceModeInit;
```

**Comment by duannx** [comment]
@utsabc @saikumarrs Please take a look at this issue.

**Comment by saikumarrs** [comment]
@duannx Thanks for raising the issue.
JS SDK has been updated (v2.4.2) to allow the execution of APIs before the `load` call. Please verify if that suffices.
Meanwhile, we are also working on the other suggestions you've provided, and we'll give you an update soon.
Thanks for being patient.

**Comment by duannx** [comment]
@saikumarrs Thank you for your response. I saw the SDK is updated but the app code is needed to update too because it currently overwrites the `window.rudderanalytics` object. Glad to hear that you are working on it. 
I am looking forward to your update!

**Comment by duannx** [comment]
Hi @saikumarrs, is there any update on this issue?

**Comment by utsabc** [comment]
> Hi @saikumarrs, is there any update on this issue?

Hey @duannx we were not able to pick up this, will be picking this up by mid of June.

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.
