### ISSUE TITLE
Ability to set configUrl and destSDKBaseURL

### ISSUE THREAD

**Issue by brandfocus** [rudderlabs/rudder-shopify-tracker#19]
Currently, it's not possible to set the `configUrl` and `destSDKBaseURL`. Is this something that could easily be added?

**Comment by utsabc** [comment]
@brandfocus the `configUrl` is currently set our production config can you please let use know why you need to update the config URL?
And secondly can you explain what do you mean by `destSDKBaseURL` ?

**Comment by brandfocus** [comment]
We load Rudderstack from behind our CDN. See https://www.rudderstack.com/docs/user-guides/how-to-guides/custom-domains/#fetching-the-source-configuration and https://www.rudderstack.com/docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/version-migration-guide/#case-3-self-hosting-rudderstacks-cdn

This helps get around cases where the Rudderstack SDK is blocked by adblockers.

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.
